In [1]:
import tensorflow as tf
import time,numpy
from sys import getsizeof

In [2]:
A = numpy.random.random([2001,2001])
#print(A)
mem = getsizeof(A)
print("Memory allocated: {:.3f} Megabytes".format(mem/1024/1024))

Memory allocated: 30.548 Megabytes


## Svd

### Numpy, cpu

In [3]:
start = time.time()
u,s,v = numpy.linalg.svd(A)
print("Temps d'exécution: {:.3f} secondes".format(time.time()-start))
print(s[:5])

Temps d'exécution: 0.769 secondes
[ 500.9588133    18.07021236   18.03339389   18.01782206   17.82454317]


### Tensorflow, cpu

In [4]:
sess = tf.InteractiveSession()
sess.as_default()

with tf.device('/cpu:0'):
    s, v, u = tf.svd(A)

start = time.time()
for i in range(1):
    res = s.eval()
    #res = sess.run(s)
print("Temps d'exécution: {:.3f} secondes".format(time.time()-start))
print(res[:5])

Temps d'exécution: 2.631 secondes
[ 500.9588133    18.07021236   18.03339389   18.01782206   17.82454317]


### Tensorflow, gpu

In [5]:
sess = tf.InteractiveSession()
sess.as_default()

with tf.device('/gpu:0'):
    s, v, u = tf.svd(A)

start = time.time()
for i in range(1):
    res = s.eval()
    #res = sess.run(s)
print("Temps d'exécution: {:.3f} secondes".format(time.time()-start))
print(res[:5])

Temps d'exécution: 2.607 secondes
[ 500.9588133    18.07021236   18.03339389   18.01782206   17.82454317]


## Multiplication de matrices

### Numpy, cpu

In [3]:
start = time.time()
for i in range(1):
    B = numpy.dot(A,A)
print("Temps d'exécution: {:.3f} secondes".format(time.time()-start))
print(B[:3,:3])

Temps d'exécution: 0.394 secondes
[[ 495.7560973   505.31396242  484.8570708 ]
 [ 513.00679369  502.82144201  493.17051005]
 [ 499.11819616  498.39695839  488.03615586]]


### Tensorflow, cpu

In [9]:
sess = tf.InteractiveSession()
sess.as_default()

with tf.device('/cpu:0'):
    B = tf.matmul(A,A)

start = time.time()
for i in range(1):
    res = sess.run(B)
print("Temps d'exécution: {:.3f} secondes".format(time.time()-start))

devices = sess.list_devices()
for d in devices:
    print(d.name)
sess.close()

Temps d'exécution: 2.635 secondes
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0


### Tensorflow, gpu

In [8]:
sess = tf.InteractiveSession()
sess.as_default()

with tf.device('/gpu:0'):
    B = tf.matmul(A,A)

start = time.time()
for i in range(1):
    res = sess.run(B)
print("Temps d'exécution: {:.3f} secondes".format(time.time()-start))

devices = sess.list_devices()
for d in devices:
    print(d.name)
sess.close()

Temps d'exécution: 2.522 secondes
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0


In [16]:
sess = tf.InteractiveSession()
sess.as_default()

with tf.device('/cpu:0'):
    B_cpu = tf.matmul(A,A)
with tf.device('/gpu:0'):
    B_gpu = tf.matmul(A,A)
with tf.device('/gpu:0'):
    B_gpu2 = tf.matmul(A,A)
    
start = time.time()
for i in range(1):
    res_gpu2 = sess.run(B_gpu2)
print("Temps d'exécution (gpu): {:.3f} secondes".format(time.time()-start))

start = time.time()
for i in range(1):
    res_cpu = sess.run(B_cpu)
print("Temps d'exécution (cpu): {:.3f} secondes".format(time.time()-start))

start = time.time()
for i in range(1):
    res_gpu = sess.run(B_gpu)
print("Temps d'exécution (gpu): {:.3f} secondes".format(time.time()-start))

devices = sess.list_devices()
for d in devices:
    print(d.name)
sess.close()

Temps d'exécution (gpu): 1.144 secondes
Temps d'exécution (cpu): 0.514 secondes
Temps d'exécution (gpu): 0.243 secondes
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0


In [3]:
import numpy as np
import tensorflow as tf
import time

n = 4001
X = tf.constant(np.array(np.random.randn(n,n), dtype = np.float32), dtype = tf.float32)
Y = tf.matmul(X, tf.transpose(X))

init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

a = time.time()
sess.run(Y)
print (time.time() - a)
sess.close()

Instructions for updating:
Use `tf.global_variables_initializer` instead.
4.624542713165283


In [3]:
import numpy as np
import tensorflow as tf
import time

size = 8001
x = np.array(np.random.randn(size, size), dtype = np.float32)

X = tf.placeholder(tf.float32, shape=(size, size), name=None)
Y = tf.matmul(X, X)

sess = tf.Session()

a = time.time()
sess.run(Y, feed_dict={X: x})
print (time.time() - a)

3.6510424613952637


In [4]:
import numpy as np
import time
np.random.seed(1)
n = 8001
x = np.array(np.random.randn(n,n), dtype = np.float32)
a = time.time(); x.dot(x); print (time.time() - a)

9.242243528366089
